### ISSUE TITLE
Hostile fork of JavaCC

### ISSUE THREAD

**Issue by matozoid** [javacc/javacc#170]
Hi! For the last few days we, the people from JavaParser, have been bullied by the creator of a hostile fork of JavaCC, who has also claimed http://javacc.com . This is a friendly warning to be very cautious when dealing with this person.

**Comment by zosrothko** [comment]
@matozoid Thank for the notice... From my knowledge, this person had not interacted with JavaCC up to know, but I do not have a full view of JavaCC. May be @new-javacc have some historic informations about.

**Comment by wumpz** [comment]
I think he tried (https://github.com/martinswanson/gradle-template/issues/2) but got no response.

**Comment by jrevusky** [comment]
I just realized that I specifically (using the account 'revusky') was blocked from replying to this. Is it normal for you guys to talk about people and deny them any right to reply? It's not something that I would do. In my world, that is completely improper.

The history of the so-called "fork" is laid out here: https://doku.javacc.com/doku.php?id=ancient_history and if you think I said anything at all false there, I have a [Discourse forum](https://discuss.parsers.org/t/project-history/28) set up where you could make the case. 

As for why I have not tried to *interact* with this community (this time round) the reason is simply *been there, done that*. Back in 2008, I tried to donate a fairly significant amount of work on JavaCC and the people in control of the project simply refused to review it. Since I had put so much work into it and the existing community was beyond impossible, I created a fork (called FreeCC) and in that period, I implemented some much-needed features, such as [INCLUDE](https://doku.javacc.com/doku.php?id=include) and [INJECT](https://doku.javacc.com/doku.php?id=code_injection_in_javacc_21) that are still missing from the legacy JavaCC project. (12 years later!) I also managed to externalize all the output of Java code into templates. (FreeMarker templates.) You can see what the main template for outputting the grammar productions looks like here, for example: https://github.com/javacc21/javacc21/blob/master/src/main/resources/templates/java/ParserProductions.java.ftl

I put "fork" in scare quotes above because I actually do not see this as a fork. (I decline to play that semantic game now.) This is simply the continuation of work on the JavaCC codebase that Sun open-sourced in 2003. I have investigated the question and there is simply no basis for believing that Sreeni or any of you have any more right to the canonical name than I do.  In fact, I believe that you have less right, since I am the only person in the whole history of this thing, since 2003, when the code was open-sourced, who has made any serious attempt to do anything with it. (I know that you may want to dispute that claim, but frankly, I don't think you have much of a leg to stand on there.)

Well, I have nothing more to say about this topic at the moment. It is quite easy to get in touch with me. There are various channels of communication. Frankly, it would surprise me if anybody from this community even tried to converse with me (though you could surprise me). What I fully expect you will do is what you did before, simply pretend that my work (the real work taking place in the space) simply doesn't exist. This seems to be the standard *modus operandi* of [nothingburger projects](https://doku.javacc.com/doku.php?id=nothingburger).

**Comment by jrevusky** [comment]
> @jrevusky Within the strictly GitHub scope of `https://github.com/javacc/javacc`, you had never been blocked since your GitHub account `@jrevusky` has less than 2 hours!

You're missing the point. My normal account is not jrevusky. It's @revusky. I created the jrevusky account specifically to be able to write a reply. And that is why the account is only 2 hours old!

As I said already, in my world, it is completely improper to talk about somebody and give that person no opportunity to reply. But, come to think of it, I faced this same kind of unethical behavior in my last incursion into this community back in 2008. So, you see, given my previous experience, it is hardly surprising that I have not made any attempt to be in touch with you people. 

And yes, I know you weren't present at that time. (No need to point that out, I know that.)
