### ISSUE TITLE
Broken urls for javacc releases | Error no main manifest attribute, in target/javacc.jar

### ISSUE THREAD

**Issue by albilu** [javacc/javacc#178]
Hello,

Can you tell why all download url are broken? It is impossible to download javacc at least 7.0+ releases.
Exemple for last release 7.0.8: **404 Not found**

https://github.com/javacc/javacc/archive/7.0.8.zip

Also with installation guide i am getting this error even with a fresh build from the source:

this error each time
**no main manifest attribute, in target/javacc.jar**

**Comment by zosrothko** [comment]
Hello...
Yes since 7.0.7 links are broken... Anyway, you can use and download here: [javacc-7.0.8](https://github.com/javacc/javacc/archive/javacc-7.0.8.zip)

" Error no main manifest attribute, in target/javacc.jar" This is not an error because ther are multiples "main" classes in the javacc jar: javacc, jjtree and jjdoc

**Comment by nodermatt** [comment]
You have to run javacc from the scripts folder of the javacc repository. Not execute the build jar with java -jar
```
 D:\SyntaxChecker> javacc .\SyntaxChecker.jj
```
