### ISSUE TITLE
Character code is returned instead of the symbol in the message

### ISSUE THREAD

**Issue by yurkom** [javacc/javacc#243]
Before
```
    Lexical error at line 1, column 6.  Encountered: "^" (94), after : "^"
```
After
```
    Lexical error at line 1, column 6.  Encountered: '94' (94), after prefix "^"
```

It was introduced in 31ba95d2383f11902030c67b2a7cb291608471d8

**Comment by zosrothko** [comment]
@MarcMazas Could you have a look at this issue since it seems it is coming from one of your change.

**Comment by MarcMazas** [comment]
Line 106 of src/main/resources/templates/TokenMgrError.template sould be

(EOFSeen ? "<EOF>" : ("'" + addEscapes(String.valueOf(curChar1)) + "' (" + (int)curChar + "),")) + //

Instead of

(EOFSeen ? "<EOF>" : ("'" + addEscapes(String.valueOf(curChar)) + "' (" + (int)curChar + "),")) + //

De : Francis ANDRE ***@***.***>
Envoyé : samedi 20 août 2022 18:51
À : javacc/javacc ***@***.***>
Cc : MAZAS Marc ***@***.***>; Mention ***@***.***>
Objet : Re: [javacc/javacc] Character code is returned instead of the symbol in the message (Issue #243)


@MarcMazas<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMarcMazas&data=05%7C01%7Cmarc.mazas%40soprasteria.com%7C765c3d4fe387499241bc08da82cc281d%7C8b87af7d86474dc78df45f69a2011bb5%7C0%7C0%7C637966110610722446%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zQKoPPmjP91y8fRVjBYSeAnvr5l1vXM1Yrqgf%2BfTapw%3D&reserved=0> Could you have a look at this issue since it seems it is coming from one of your change.

-
