### ISSUE TITLE
Master vs Tag 7.0.12

### ISSUE THREAD

**Issue by manticore-projects** [javacc/javacc#254]
Greetings.

As promised I started to look into the deployment and documentation.
Naturally, I would have expected the branch MASTER is the latest, however it points to 7.0.11-SNAPSHOT. Then there is a Tag 7.0.12 which points to 7.0.12 correctly. I do not see a DEVELOPMENT branch either.

Am I misunderstanding something here?
What branch will hold the latest changes and development?

Suggestion:

Would you accept a PR, which derives the actual Version from GIT Tags and updates the POM and the documentation accordingly?

**Comment by zosrothko** [comment]
@manticore-projects I resyncked the tag javacc-7.0.12 with the master branch. There should be no more version of the JavaCC 7 release as by now. All new developments should go to JavaCC 8 as per request of the owner @new-javacc .

By the way if you want to contibute, could you ask to Sreeni to be an admin of JavaCC since I will retired myself by end of this month.

**Comment by manticore-projects** [comment]
Thanks, I will take it up from here.
Happy retirement and cheers!

**Comment by new-javacc** [comment]
Thank you very much, Andreas for stepping in!

And a very big thank you to Francis for all the work in keeping the 
lights on over the last 5+ years on this project.

Sreeni.

**Comment by manticore-projects** [comment]
Sreeni and Team,

I am finally back home and ready to pick that up.
I would like to suggest implementing similar things like shown before:

1) Switch to Sphinx (which is easier, more powerful for technical doc and more reliable to deploy, real TOC, index, PDF print and so on)
2) Implement proper versioning based on Sphinx Prologue Variables/Placeholders
3) Add a proper Change log page
4) Maybe add a RR diagram about the Java CC Grammar
5) Fix the broken samples and dead links
6) Write a section about JavaCC 8

7) Optionally: provide Unicode Character Tokens for each Unicode Category
8) Optionally: maybe add a Gradle Build (since I really do not like Maven)

Please let me know any sacrosanct  parts, which I am not supposed to touch.
Since this will be about infrastructure, it would be hard to provide incremental patches. Although I don't think its necessary since I won't touch the JavaCC itself (yet). Instead I would branch it and show results first from where you can pick what to pull in.

Cheers
Andreas

**Comment by new-javacc** [comment]
Sounds great!On Jan 21, 2023 6:19 AM, manticore-projects ***@***.***> wrote:
Sreeni and Team,
I am finally back home and ready to pick that up.
I would like to suggest implementing similar things like shown before:

Switch to Sphinx (which is easier, more powerful for technical doc and more reliable to deploy, real TOC, index, PDF print and so on)

Implement proper versioning based on Sphinx Prologue Variables/Placeholders

Add a proper Change log page

Maybe add a RR diagram about the Java CC Grammar

Fix the broken samples and dead links

Write a section about JavaCC 8

Optionally: provide Unicode Character Tokens for each Unicode Category

Optionally: maybe add a Gradle Build (since I really do not like Maven)

Please let me know any sacrosanct  parts, which I am not supposed to touch.
Since this will be about infrastructure, it would be hard to provide incremental patches. Although I don't think its necessary since I won't touch the JavaCC itself (yet). Instead I would branch it and show results first from where you can pick what to pull in.
Cheers
Andreas

**Comment by MarcMazas** [comment]
Closed as outdated.
