### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by matozoid** [javacc/javacc#37]
We're all waiting :-) https://github.com/phax/ph-javacc-maven-plugin/issues/2

**Comment by kaikalur** [comment]
Guys, my current level of confidence in the 7.x version is very low. It seems to be broken - especially for C++. So I'm not sure how to proceed. I'm working on something different - like C# code generator etc. that will hopefully streamline the code base so that code generators can be done completely outside instead of the 100s of weird/bad options (like LEGACY_EXCEPTION_HANDLING which I dislike very much).

or now, may be we simply branch from the 7.0 release and patch for these couple of issues and release it?

**Comment by phax** [comment]
A minor level release would really be appreciated.
So a 7.0.3 release with just my PR and maybe other general patches would do the trick and remove the pressure - can you do that?

**Comment by zosrothko** [comment]
@new-javacc Did you finish to merge  your changes in the master branch so that I can push a release to MAven Central?

**Comment by kaikalur** [comment]
Not sure what you mean by that. I'm not sure current 7.x is in a good shape to push.That's why I'm thinking we just take the two simple fixes that they are talking about On Nov 4, 2017 12:05 AM, zosrothko <notifications@github.com> wrote:@new-javacc Did you finish to merge  your changes in the master branch so that I can push a release to MAven Central?

**Comment by zosrothko** [comment]
@kaikalur "Not sure what you mean by that. I'm not sure current 7.x is in a good shape to push." Can you elaborate/explain? Have you counter examples of JavaCC grammar for C++ that do not work?

**Comment by zosrothko** [comment]
There is already a staging  [JavaCC 7.0.3 artifact](https://oss.sonatype.org/content/repositories/netjavadevjavacc-1010). The final release to Maven Central depends on Sreeni's go answer.
```
<dependency>
  <groupId>net.java.dev.javacc</groupId>
  <artifactId>javacc</artifactId>
  <version>7.0.3</version>
</dependency>
```

**Comment by new-javacc** [comment]
(Sorry guys, @kaikalur is also me. By mistake I posted from the other 
account).

That's not how this works. The three times I tried the c++ version over 
the last month, I found 3 issues. That makes me think I should 
thoroughly review the new C++ code generator. AND make it a beta. I see 
significant changes and I  want to make sure they are safe - C++ is 
especially nasty.

So my suggestion would be to have two different releases - 7.0.3 just 
patches to the previous release of 7.0  - that are simple and easy to 
verify. Then 7.1 will be a separate beta release and we can make it 
later after some more thorough testing.

General suggestion - the original generated C++ code was purposely kept 
really simple AND did not use exceptions and/or any libraries so we can 
easily track things like memory leaks etc. So I suggest keeping the 
default C++ code generator  to be just as it was in 7.0 and use your 
enhanced version as an alternate code generator after my refactoring - 
8.0. Looks like only @zosrothko really needs this change and since he is 
the developer, he can just keep working on it and using it.

I always took great pride in JavaCC having  very very few bugs if any 
and I want to maintain that standard.

Let me know what you all think.

Sreeni.

**Comment by zosrothko** [comment]
@new-javacc can you create the 7.1.0 branch from master?

**Comment by phax** [comment]
No problem.

> 7.0.3 just patches to the previous release of 7.0

does the trick for me :)
So just take the 7.0.2 release, apply PR #29 and everybody is happy 😄

**Comment by zosrothko** [comment]
@phax You are right except that I do not have write access anymore ... @new-javacc will have to do it as well as the release to Maven

**Comment by kaikalur** [comment]
Sorry guys! I will restore access to @zosrothko ASAP so he can do it. 
I'm busy right now with some other stuff and also I'm not 100% 
comfortable working with github (I'm old :()

Sreeni.

**Comment by new-javacc** [comment]
And I also suggest using  pull requests to merge into any core javacc 
changes from now on so that I can keep an eye on things. Thanks!

**Comment by new-javacc** [comment]
Hello all,

I just re-added @zosrothko as a contributor to this repository.

Thanks,
Kesav

**Comment by kaikalur** [comment]
Thanks, Kesav!@zosrothko, please go ahead and release 7.0.3.On Nov 4, 2017 8:54 PM, JavaCC Support <notifications@github.com> wrote:Hello all,
I just re-added @zosrothko as a contributor to this repository.
Thanks,
Kesav

**Comment by zosrothko** [comment]
JavaCC 7.0.3 released on GitHub and in Maven Central

**Comment by matozoid** [comment]
Thank you all!

**Comment by new-javacc** [comment]
Thank you, @zosrothko!

**Comment by phax** [comment]
https://javacc.org/download is still referncing v6 :)
