### ISSUE TITLE
cannot find symbol JavaCharStream.staticFlag

### ISSUE THREAD

**Issue by jan-niestadt** [javacc/javacc#95]
A parser generated with 7.0.4 doesn't compile because it cannot find JavaCharStream.staticFlag.

These are my parser options:
```
options 
{
	STATIC=false;
	JAVA_UNICODE_ESCAPE=true;
}
```

I get these compilation errors:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project blacklab: Compilation failure: Compilation failure:
[ERROR] /home/jan/projects/blacklab/core/src/main/java/nl/inl/blacklab/queryParser/contextql/GeneratedContextualQueryLanguageParserTokenManager.java:[609,25] cannot find symbol
[ERROR] symbol:   variable staticFlag
[ERROR] location: class nl.inl.blacklab.queryParser.contextql.JavaCharStream
[ERROR] /home/jan/projects/blacklab/core/src/main/java/nl/inl/blacklab/queryParser/contextql/GeneratedContextualQueryLanguageParserTokenManager.java:[609,10] illegal start of type
```

This is the code referred to:
```java
/** Constructor. */
public GeneratedContextualQueryLanguageParserTokenManager(JavaCharStream stream){
  if (JavaCharStream.staticFlag)
    throw new RuntimeException("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
  input_stream = stream;
}
```

The generated JavaCharStream class doesn't have a staticFlag variable, hence the error.

If I comment out the if statement, it seems to work.

**Comment by new-javacc** [comment]
You may have to delete the old version first.On Jul 30, 2019 3:02 AM, Jan Niestadt <notifications@github.com> wrote:A parser generated with 7.0.4 doesn't compile because it cannot find JavaCharStream.staticFlag.
These are my parser options:
options 
{
	STATIC=false;
	JAVA_UNICODE_ESCAPE=true;
}

I get these compilation errors:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project blacklab: Compilation failure: Compilation failure:
[ERROR] /home/jan/projects/blacklab/core/src/main/java/nl/inl/blacklab/queryParser/contextql/GeneratedContextualQueryLanguageParserTokenManager.java:[609,25] cannot find symbol
[ERROR] symbol:   variable staticFlag
[ERROR] location: class nl.inl.blacklab.queryParser.contextql.JavaCharStream
[ERROR] /home/jan/projects/blacklab/core/src/main/java/nl/inl/blacklab/queryParser/contextql/GeneratedContextualQueryLanguageParserTokenManager.java:[609,10] illegal start of type

This is the code referred to:
/** Constructor. */
public GeneratedContextualQueryLanguageParserTokenManager(JavaCharStream stream){
  if (JavaCharStream.staticFlag)
    throw new RuntimeException("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
  input_stream = stream;
}
The generated JavaCharStream class doesn't have a staticFlag variable, hence the error.
If I comment out the if statement, it seems to work.

**Comment by jan-niestadt** [comment]
Thanks, I did delete all the old generated files but an incorrect version keeps being generated. I am using javacc from Maven though, using [ph-javacc-maven-plugin 4.1.3](https://github.com/phax/ph-javacc-maven-plugin).

I tried running javacc from the commandline (versions 5.0 and 6.0) and that works as it should. So it seems the problems is with the Maven plugin. I'll ask there.

**Comment by jan-niestadt** [comment]
Ok, I actually realised `ph-javacc-maven-plugin` doesn't use javacc (misleading name), sorry. I switched to `org.codehaus.mojo.javacc-maven-plugin` and that works properly. Thanks!

**Comment by phax** [comment]
@jan-niestadt I wil check after my vacation

**Comment by phax** [comment]
@jan-niestadt as background: I forked JavaCC to ParserGeneratorCC (https://github.com/phax/ParserGeneratorCC/) to be more flexible in adopting things. Things droped were e.g. the support for Java versions 1.5 as well as support for "static" parsers. Therefore the `staticFlag` no longer exists.
And concerning the `ph-javacc-maven-plugin` - that was forked, because the Codehaus plugin development stalled and I needed a later JavaCC versions.
Can you please elaborate, where the `staticFlag` comes from? Are you sure it isn't part of your grammar?

**Comment by jan-niestadt** [comment]
@phax the plugin was generating code that referred to staticFlag but the flag itself wasnt' generated. It's not in my grammar. I did include javacc as a depency though, maybe that caused it?

Anyway, JavaCC and the Codehaus plugin work for me at the moment, so I will stick with those.

**Comment by phax** [comment]
@jan-niestadt Thanks for the clarification. If you want, you can provide me the grammar by email, so that I could try to figure out what the issue is (ph at helger.com) - thx
